### PR TITLE
Remove desugaring

### PR DESCRIPTION
**Pull request by smihalic**
## :pencil: Changes
There was an issue when updating AGP version from 8.0 to 8.3 where a project that uses sentinel would need to have desugaring enabled. Removing this also removes the need to add desugaring in other projects.

### CODE REVIEW

**Comment by KCeh** [comment]
Correct, upgrading AGP to 8.3.0 will result in clients of library needing to use desugaring (https://issuetracker.google.com/issues/329346764) 
So I agree it is probably better to remove it. But then we also need to change the code that is affected by this change.

**Comment by AsimRibo** [comment]
@KCeh since removal of desugaring will take a lot more work, should we close this PR?

**Comment by KCeh** [comment]
> @KCeh since removal of desugaring will take a lot more work, should we close this PR?

You are correct, it will take a lot more work. But let's keep it as a starting point. I will switch it to draft

**Comment by KCeh** [comment]
I have removed desugaring from Sentinel.
Sentinel's version of `ChronoUnit` is introduced to avoid the need for DB refactoring. Other than that in place where Java 8 Time API is needed checks and Require annotations are added. Therefore, certificate tools is no longer supported on devices API < 26

**Review by AsimRibo — APPROVED** [review]
Looks good. Works good.

**Pull request merged**
